name: open_transit_app
description: An open public transportation data platform
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_map: ^6.0.0-dev.3
  flutter_map_cancellable_tile_provider: ^1.0.0-preview
  flutter_riverpod: ^2.4.0
  freezed_annotation: ^2.4.1
  go_router: ^10.1.2
  latlong2: ^0.9.0
  logger: ^2.0.2
  package_info_plus: ^4.1.0
  riverpod_annotation: ^2.1.5
  shared_preferences: ^2.2.1
  sliding_up_panel: ^2.0.0+1
  url_launcher: ^6.1.14

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  riverpod_generator: ^2.3.2
  riverpod_lint: ^2.1.0

dependency_overrides:
  dio:
    git:
      url: https://github.com/lonelyteapot/dio.git
      ref: patch-1
      path: dio
  flutter_map:
    git:
      url: https://github.com/fleaflet/flutter_map.git
      ref: d35d672757ddc9669f99a5c1cd370749e927198d

flutter:
  uses-material-design: true
