name: open_transit_app
description: An open public transportation data platform
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  decimal: ^2.3.3
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_map: ^6.0.0
  flutter_map_cancellable_tile_provider: ^2.0.0
  flutter_riverpod: ^2.4.0
  freezed_annotation: ^2.4.1
  go_router: ^13.2.3
  graphql: ^5.2.0-beta.6
  http: ^1.1.0
  json_annotation: ^4.8.1
  latlong2: ^0.9.0
  logger: ^2.0.2
  package_info_plus: ^7.0.0
  riverpod_annotation: ^2.1.5
  shared_preferences: ^2.2.1
  sliding_up_panel: ^2.0.0+1
  url_launcher: ^6.1.14

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.6.4
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.3.2
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  integration_test:
    sdk: flutter
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#292929"
