name: open_transit_app
description: An open public transportation data platform
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_map: ^6.0.0-dev.3
  flutter_map_cancellable_tile_provider: ^1.0.0-preview
  flutter_riverpod: ^2.4.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  dio:
    git:
      url: https://github.com/lonelyteapot/dio.git
      ref: patch-1
      path: dio

flutter:
  uses-material-design: true
