name: open_transit_app
description: An open public transportation data platform
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_map: ^6.0.0-dev.3
  flutter_map_cancellable_tile_provider: ^1.0.0-preview
  flutter_riverpod: ^2.4.0
  latlong2: ^0.9.0
  shared_preferences: ^2.2.1
  sliding_up_panel: ^2.0.0+1
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  dio:
    git:
      url: https://github.com/lonelyteapot/dio.git
      ref: patch-1
      path: dio
  flutter_map:
    git:
      url: https://github.com/fleaflet/flutter_map.git
      ref: d35d672757ddc9669f99a5c1cd370749e927198d

flutter:
  uses-material-design: true
