name: Build & Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  FLUTTER_VERSION: "3.16.0-0.3.pre"
  FLUTTER_CHANNEL: "beta"

jobs:
  android_build:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"
          architecture: x64
      - name: Disable Flutter telemetry
        run: flutter --disable-analytics
      - name: Install dependencies
        run: flutter pub get --enforce-lockfile
      - name: Build for Android
        run: flutter build apk --dart-define MAPBOX_ACCESS_TOKEN=${{ secrets.MAPBOX_ACCESS_TOKEN }}
      - name: Upload Android artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-build
          path: build/app/outputs/flutter-apk/
          retention-days: 7

  web_build:
    name: Build for Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"
          architecture: x64
      - name: Disable Flutter telemetry
        run: flutter --disable-analytics
      - name: Install dependencies
        run: flutter pub get --enforce-lockfile
      - name: Build for Web
        run: flutter build web --web-renderer canvaskit --dart-define MAPBOX_ACCESS_TOKEN=${{ secrets.MAPBOX_ACCESS_TOKEN }}
      - name: Upload Web artifact
        uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: build/web/
          retention-days: 7

  deploy:
    name: Deploy to GitHub Pages
    needs: [android_build, web_build]
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Download Web artifact
        uses: actions/download-artifact@v3
        with:
          name: web-build
          path: dist
      - name: Download Android artifact
        uses: actions/download-artifact@v3
        with:
          name: android-build
          path: android
      - name: Move Android APK
        run: |
          mkdir dist/downloads
          mv android/app-release.apk dist/downloads/open-transit-dev.apk
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: dist
          retention-days: 7
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
