name: Build & Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build for Web & Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.0-0.3.pre"
          channel: "beta"
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"
          architecture: x64
      - name: Disable Flutter telemetry
        run: flutter --disable-analytics
      - name: Install dependencies
        run: flutter pub get --enforce-lockfile
      - name: Build for Android
        run: flutter build apk --dart-define MAPBOX_ACCESS_TOKEN=${{ secrets.MAPBOX_ACCESS_TOKEN }}
      - name: Build for Web
        run: flutter build web --base-href="/open-transit-app/" --web-renderer canvaskit --dart-define MAPBOX_ACCESS_TOKEN=${{ secrets.MAPBOX_ACCESS_TOKEN }}
      - name: Copy APK to the website
        run: mv build/app/outputs/flutter-apk/app-release.apk build/web/open-transit.apk
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: build/web
          retention-days: 7
  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
